### ISSUE TITLE
Provide stable symlinks for something $latest build

### ISSUE THREAD

**Issue by felixb** [flosell/lambdacd-artifacts#2]
I'd be useful to resolve something like `/artifacts/latest/5-2/artifact.txt` to `/artifcats/9001/5-2/artifacts.txt`.

**Comment by flosell** [comment]
Sounds like a useful feature. 

Two assumptions that come to my mind, please correct me if I'm wrong: 
- We are looking for the the latest available artifact, not necessarily the latest build. The latest build might not have created the artifact you are looking for (e.g. because it failed or is still running)
- We assume that an artifact is good and can be selected as the latest artifact if it was published (using `publish-artifact`), even the step or the pipeline failed later on. 

Let me know if you want to take a stab at this yourself, I'd welcome a PR. If not, I'll probably implement this myself soon(ish). 

Possible implementation: (in `file-result`)
- list all the builds in the home-dir
- find builds that have the desired file
- sort and get the latest

The latest build(s) might have failed before even building the artifact you are looking for so just looking up  the latest build in `ctx` probably won't be enough.

**Comment by felixb** [comment]
I'll try to do it myself until end of next week.
